"""
static_analysis.py
==================
Módulo de análisis estático del lenguaje de reglas.

Detecta tres categorías de problemas sin necesitar ejecutar (re-ejecutar)
el intérprete:

1. CONFLICTO
   Múltiples reglas con la MISMA acción pero DISTINTA condición.
   Formato de salida: "Action <id> generated by r1, r2, ..."

2. REDUNDANCIA
   Grupo de reglas que tienen IDÉNTICA condición e IDÉNTICA acción.
   Formato de salida: "Redundant rules: r1, r2"

3. REGLA POTENCIALMENTE INACTIVA
   Una regla que, dado el estado inicial, NUNCA disparará, y además está
   completamente aislada de la red de propagación de hechos:
       • Su acción no es usada como condición de hecho en ninguna otra regla.
       • Su condición no depende de hechos producidos por otras reglas.
       • Sus comparaciones de variables son probablemente falsas con el
         estado dado (si la variable está definida y el valor no satisface
         la comparación).
   Formato de salida: "Potentially inactive rule: <id>"

Criterio de la regla potencialmente inactiva — justificación:
    Consideramos solo las reglas "aisladas" (sin aristas entrantes ni
    salientes en el grafo de dependencias de hechos). Si además su condición
    es probablemente insatisfacible con los valores concretos del estado
    inicial, la marcamos como potencialmente inactiva. Esto evita falsos
    positivos en reglas que forman parte de cadenas (aunque tampoco
    disparen), ya que su inactividad es "explicada" por otra regla.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Set, Tuple

from ast_nodes import (
    AndCondition,
    CompCondition,
    Condition,
    FactCondition,
    Program,
    Rule,
)


# ---------------------------------------------------------------------------
# Utilidades sobre condiciones
# ---------------------------------------------------------------------------

def _condition_canonical(cond: Condition) -> str:
    """
    Produce una representación canónica (única) de una condición.

    Para condiciones AND aplana todos los átomos y los ORDENA
    lexicográficamente, de modo que:
        (a AND b)  y  (b AND a)
    produzcan la misma cadena (útil para detectar redundancias).
    """
    if isinstance(cond, CompCondition):
        return f"({cond.identifier}{cond.operator}{cond.value})"
    elif isinstance(cond, FactCondition):
        return f"({cond.identifier})"
    elif isinstance(cond, AndCondition):
        atoms = _collect_atoms(cond)
        return "AND".join(sorted(atoms))
    return ""


def _collect_atoms(cond: Condition) -> List[str]:
    """
    Aplana un árbol de AND en una lista plana de cadenas atómicas.
    Permite normalizar condiciones AND sin importar la asociatividad.
    """
    if isinstance(cond, AndCondition):
        return _collect_atoms(cond.left) + _collect_atoms(cond.right)
    return [_condition_canonical(cond)]


def _get_fact_deps(cond: Condition) -> Set[str]:
    """
    Extrae los identificadores de todos los FactCondition presentes
    en la condición (no los de CompCondition, que son variables).
    Son los hechos de los que depende esta condición para disparar.
    """
    if isinstance(cond, FactCondition):
        return {cond.identifier}
    elif isinstance(cond, AndCondition):
        return _get_fact_deps(cond.left) | _get_fact_deps(cond.right)
    return set()  # CompCondition no tiene dependencias de hechos


def _is_provably_inactive(
    cond:        Condition,
    state_vars:  Dict[str, int],
    state_facts: Set[str],
) -> bool:
    """
    Determina si una condición es PROBABLEMENTE INSATISFACIBLE dado el estado.

    Reglas:
      - CompCondition(x, op, v):
            Si 'x' está definido en state_vars y la comparación falla → True.
            Si 'x' NO está definido → False (conservador: no sabemos su valor).
      - FactCondition(x):
            Devuelve False aquí; la inaccesibilidad de hechos se maneja
            mediante la comprobación de dependencias de reglas.
      - AndCondition:
            True si CUALQUIERA de las sub-condiciones es probablemente
            insatisfacible (AND falla si al menos uno falla).
    """
    if isinstance(cond, CompCondition):
        val = state_vars.get(cond.identifier)
        if val is None:
            # Variable no definida en el estado → no podemos afirmar que sea falsa.
            return False
        op, v = cond.operator, cond.value
        if op == ">": return not (val > v)
        if op == "<": return not (val < v)
        if op == "=": return not (val == v)
        return False

    elif isinstance(cond, FactCondition):
        # Tratado por las comprobaciones de dependencias, no aquí.
        return False

    elif isinstance(cond, AndCondition):
        # AND es falso si cualquier sub-condición es probablemente falsa.
        return (
            _is_provably_inactive(cond.left,  state_vars, state_facts)
            or _is_provably_inactive(cond.right, state_vars, state_facts)
        )

    return False


# ---------------------------------------------------------------------------
# Detección de conflictos
# ---------------------------------------------------------------------------

def detect_conflicts(rules: List[Rule]) -> List[str]:
    """
    Detecta conflictos: múltiples reglas con la MISMA acción pero
    con condiciones distintas.

    Si todas las reglas de un grupo tienen condición idéntica, es redundancia
    y NO se reporta aquí como conflicto.

    Devuelve:
        Lista de mensajes ordenada alfabéticamente por identificador de acción.
        Formato: "Action <id> generated by r1, r2, ..."
    """
    # Agrupar reglas por el identificador de su acción
    action_groups: dict[str, List[Rule]] = defaultdict(list)
    for rule in rules:
        action_groups[rule.action.identifier].append(rule)

    messages: List[str] = []

    for action_id, group in sorted(action_groups.items()):
        if len(group) <= 1:
            continue  # Una sola regla → sin conflicto

        # Calcular formas canónicas de las condiciones
        canonical_set = {_condition_canonical(r.condition) for r in group}

        if len(canonical_set) == 1:
            # Todas idénticas → es redundancia, no conflicto
            continue

        # Distintas condiciones con la misma acción → CONFLICTO
        rule_names = ", ".join(sorted(r.name for r in group))
        messages.append(f"Action {action_id} generated by {rule_names}")

    return messages


# ---------------------------------------------------------------------------
# Detección de redundancias
# ---------------------------------------------------------------------------

def detect_redundancies(rules: List[Rule]) -> List[str]:
    """
    Detecta redundancias: grupos de reglas con IDÉNTICA condición e
    IDÉNTICA acción.

    Devuelve:
        Lista de mensajes, uno por cada grupo redundante.
        Formato: "Redundant rules: r1, r2"
    """
    # Agrupar por (forma_canónica_condición, acción)
    groups: dict[Tuple[str, str], List[str]] = defaultdict(list)
    for rule in rules:
        key = (_condition_canonical(rule.condition), rule.action.identifier)
        groups[key].append(rule.name)

    messages: List[str] = []

    for key, names in groups.items():
        if len(names) > 1:
            names_str = ", ".join(sorted(names))
            messages.append(f"Redundant rules: {names_str}")

    return sorted(messages)  # Ordenar mensajes entre sí


# ---------------------------------------------------------------------------
# Detección de reglas potencialmente inactivas
# ---------------------------------------------------------------------------

def detect_inactive(
    rules:       List[Rule],
    state_vars:  Dict[str, int],
    state_facts: Set[str],
    fired_rules: Set[str],
) -> List[str]:
    """
    Detecta reglas potencialmente inactivas.

    Una regla se considera potencialmente inactiva si TODOS los criterios
    siguientes se cumplen simultáneamente:

    1. Nunca disparó durante la ejecución (fired_rules no la contiene).

    2. Su acción NO es usada como FactCondition en ninguna otra regla.
       (No tiene "sucesores" en el grafo de dependencias de hechos.)

    3. Su condición NO contiene FactConditions cuyo identificador sea la
       acción de alguna otra regla. (No tiene "predecesores" en el grafo.)
       → Esto excluye reglas cuya inactividad es "explicada" por la
         inactividad de otra regla de la que dependen.

    4. Su condición es PROBABLEMENTE INSATISFACIBLE con el estado dado.
       → Si la variable está definida en state_vars y el valor no supera
         la comparación, la condición es provablemente falsa.
       → Si la variable NO está definida, no podemos afirmarlo (conservador).

    Devuelve:
        Lista de mensajes ordenada alfabéticamente por nombre de regla.
        Formato: "Potentially inactive rule: <id>"
    """
    # Conjunto de todos los identificadores producidos como acción por cualquier regla
    all_rule_actions: Set[str] = {r.action.identifier for r in rules}

    messages: List[str] = []

    for rule in rules:
        # ── Criterio 1: la regla nunca disparó ─────────────────────────────
        if rule.name in fired_rules:
            continue

        # ── Criterio 2: la acción de la regla no la usa ninguna otra ────────
        action_used = any(
            rule.action.identifier in _get_fact_deps(r.condition)
            for r in rules
            if r.name != rule.name
        )
        if action_used:
            continue  # La acción alimenta a otra regla → no la reportamos

        # ── Criterio 3: la condición no depende de hechos de otras reglas ───
        fact_deps_in_cond = _get_fact_deps(rule.condition)
        depends_on_rule_outputs = bool(fact_deps_in_cond & all_rule_actions)
        if depends_on_rule_outputs:
            continue  # Su condición depende de hechos generados por reglas

        # ── Criterio 4: la condición es probablemente insatisfacible ─────────
        if not _is_provably_inactive(rule.condition, state_vars, state_facts):
            continue  # No podemos afirmar que sea inactiva con este estado

        messages.append(f"Potentially inactive rule: {rule.name}")

    return sorted(messages)  # Orden lexicográfico


# ---------------------------------------------------------------------------
# Función principal del módulo
# ---------------------------------------------------------------------------

def analyze(
    program:     Program,
    state_vars:  Dict[str, int],
    state_facts: Set[str],
    fired_rules: Set[str],
) -> Tuple[List[str], List[str], List[str]]:
    """
    Ejecuta los tres análisis estáticos sobre el programa.

    Args:
        program     : AST del programa.
        state_vars  : variables enteras del estado inicial.
        state_facts : hechos activos del estado inicial.
        fired_rules : conjunto de nombres de reglas que dispararon.

    Returns:
        Tupla (conflict_msgs, redundancy_msgs, inactive_msgs).
        Cada elemento es una lista de cadenas listas para imprimir.
    """
    rules = program.rules

    conflict_msgs   = detect_conflicts(rules)
    redundancy_msgs = detect_redundancies(rules)
    inactive_msgs   = detect_inactive(rules, state_vars, state_facts, fired_rules)

    return conflict_msgs, redundancy_msgs, inactive_msgs
